// examples/frontends/svelte/src/App.svelte
<script lang="ts">
  import {
    FramekitAuthenticationError,
    FramekitAuthorizationError,
    FramekitConflictError,
    FramekitSdkError,
    FramekitServerError,
    FramekitTransportError,
    FramekitValidationError,
    FramekitClient
  } from "@framekit/sdk";
  import { onDestroy, onMount } from "svelte";

  type CustomerData = {
    name: string;
    status: "active" | "paused";
    owner: string;
    annual_revenue: string;
  };

  type CustomerRecord = {
    id: string;
    data: CustomerData;
  };

  type MetaSnapshot = { app?: { name?: string; version?: string }; name?: string; version?: string };

  const apiUrl = import.meta.env.VITE_FRAMEKIT_API_URL ?? "";
  const tenantId = import.meta.env.VITE_FRAMEKIT_TENANT_ID ?? "default";
  const appName = import.meta.env.VITE_FRAMEKIT_APP_NAME ?? "CRM";
  const userId = import.meta.env.VITE_FRAMEKIT_USER_ID ?? "frontend";
  function createClient() {
    return new FramekitClient({
      version: 2,
      baseUrl: apiUrl,
      authMode: "bearer",
      tenant: { tenantId, userId, roles: ["administrator"], permissions: ["*"] }
    });
  }

  let client = createClient();
  let sessionGeneration = 0;
  let mounted = true;
  let refreshController: AbortController | null = null;
  let createController: AbortController | null = null;

  let customers = $state<CustomerRecord[]>([]);
  let health = $state<"checking" | "online" | "offline">("checking");
  let meta = $state<MetaSnapshot | null>(null);
  let loading = $state(false);
  let submitting = $state(false);
  let authenticating = $state(false);
  let signedIn = $state(false);
  let error = $state<string | null>(null);
  let notice = $state<string | null>(null);
  let name = $state("");
  let status = $state<CustomerData["status"]>("active");
  let owner = $state("Sales");
  let annualRevenue = $state("0.00");
  let email = $state("admin@example.com");
  let password = $state("");

  onMount(() => {
    void checkHealth();
  });

  onDestroy(() => {
    mounted = false;
    invalidateSession();
  });

  function abortProtectedRequests() {
    refreshController?.abort();
    createController?.abort();
    refreshController = null;
    createController = null;
  }

  function invalidateSession() {
    sessionGeneration += 1;
    abortProtectedRequests();
  }

  function isCurrent(generation: number, requestClient: FramekitClient) {
    return mounted && generation === sessionGeneration && client === requestClient;
  }

  async function checkHealth() {
    const generation = sessionGeneration;
    const requestClient = client;
    health = "checking";
    try {
      const healthResponse = await requestClient.health();
      if (!isCurrent(generation, requestClient)) return;
      health = healthResponse.ok ? "online" : "offline";
    } catch (cause) {
      if (!isCurrent(generation, requestClient)) return;
      health = "offline";
      error = presentError(cause);
    }
  }

  async function refresh() {
    if (!signedIn) return;
    refreshController?.abort();
    const controller = new AbortController();
    refreshController = controller;
    const generation = sessionGeneration;
    const requestClient = client;
    loading = true;
    error = null;
    notice = null;
    try {
      const [metaResponse, page] = await Promise.all([
        requestClient.meta<MetaSnapshot>(),
        requestClient.listPage<CustomerData>("customer", { limit: 50, sort: { field: "name", direction: "asc" }, signal: controller.signal })
      ]);
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      meta = metaResponse;
      customers = page.items;
    } catch (cause) {
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, requestClient) && refreshController === controller) {
        refreshController = null;
        loading = false;
      }
    }
  }

  async function signIn() {
    invalidateSession();
    const generation = sessionGeneration;
    const loginClient = createClient();
    client = loginClient;
    authenticating = true;
    error = null;
    notice = null;
    try {
      await loginClient.login(email, password);
      if (!isCurrent(generation, loginClient)) return;
      password = "";
      signedIn = true;
      notice = "Signed in. Loading the customer ledger.";
      await refresh();
    } catch (cause) {
      if (!isCurrent(generation, loginClient)) return;
      password = "";
      signedIn = false;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, loginClient)) authenticating = false;
    }
  }

  async function signOut() {
    const logoutClient = client;
    invalidateSession();
    error = null;
    notice = null;
    try {
      await logoutClient.logout();
      if (mounted) notice = "Signed out. Your session was cleared from memory.";
    } catch (cause) {
      if (mounted) error = presentError(cause);
    } finally {
      client = createClient();
      if (!mounted) return;
      signedIn = false;
      customers = [];
      meta = null;
      password = "";
      loading = false;
      submitting = false;
    }
  }

  async function createCustomer() {
    if (!name.trim()) {
      error = "A customer name is required before an entry can be posted.";
      return;
    }
    createController?.abort();
    const controller = new AbortController();
    createController = controller;
    const generation = sessionGeneration;
    const requestClient = client;
    submitting = true;
    error = null;
    notice = null;
    const idempotencyKey = crypto.randomUUID();
    try {
      const customer = await requestClient.create<CustomerData>("customer", {
        name: name.trim(),
        status,
        owner: owner.trim() || "Sales",
        annual_revenue: annualRevenue.trim() || "0.00"
      }, { idempotencyKey, signal: controller.signal });
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      customers = [customer, ...customers];
      name = "";
      status = "active";
      owner = "Sales";
      annualRevenue = "0.00";
      notice = `Entry ${customer.id} posted to the ledger.`;
    } catch (cause) {
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, requestClient) && createController === controller) {
        createController = null;
        submitting = false;
      }
    }
  }

  function presentError(cause: unknown): string {
    if (cause instanceof FramekitValidationError) return `Validation (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitAuthenticationError) return `Authentication (${cause.status ?? "no status"}): ${cause.message}`;
    if (cause instanceof FramekitAuthorizationError) return `Permission denied (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitConflictError) return `Conflict (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitServerError) return `Server error (${cause.status ?? "unknown"}): ${cause.message}`;
    if (cause instanceof FramekitTransportError) return `Connection failed: ${cause.message}`;
    if (cause instanceof FramekitSdkError) return `Framekit ${cause.code}: ${cause.message}`;
    return cause instanceof Error ? cause.message : "An unexpected error interrupted the request.";
  }

  function money(value: unknown): string {
    const amount = Number(value);
    return Number.isFinite(amount) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount) : "—";
  }
</script>

<svelte:head><title>Customer Ledger · {appName}</title></svelte:head>

<main class="ledger-shell">
  <header class="masthead entry entry-one">
    <p class="kicker"><span class="signal" aria-hidden="true"></span> Framekit / {appName}</p>
    <div class="masthead-row">
      <h1>Customer<br /><em>ledger.</em></h1>
      <div class="terminal" aria-label="Connection details">
        <span class:online={health === "online"} class:offline={health === "offline"} class="status-dot"></span>
        <span>{health === "checking" ? "checking node" : health === "online" ? "node live" : "node unavailable"}</span>
        <small>{apiUrl || "same-origin API proxy"}</small>
      </div>
    </div>
  </header>

  <section class="context entry entry-two" aria-label="Ledger context">
    <p>Tenant <strong>{tenantId}</strong> / operator <strong>{userId}</strong></p>
    <p>{meta?.app?.name ?? meta?.name ?? appName}{meta?.app?.version ?? meta?.version ? ` · ${meta.app?.version ?? meta.version}` : ""}</p>
    {#if signedIn}
      <div class="context-actions">
        <button class="refresh" onclick={refresh} disabled={loading} aria-label="Refresh customer ledger"><span aria-hidden="true">↻</span> {loading ? "Refreshing" : "Refresh"}</button>
        <button class="refresh" onclick={() => void signOut()} aria-label="Sign out">Sign out</button>
      </div>
    {:else}
      <span class="auth-prompt">Sign in to open ledger</span>
    {/if}
  </section>

  {#if error}
    <div class="message error" role="alert"><b>Request note</b><span>{error}</span></div>
  {/if}
  {#if notice}
    <div class="message success" role="status"><b>Posted</b><span>{notice}</span></div>
  {/if}

  <div class="ledger-grid">
    <section class="register entry entry-three" aria-labelledby="register-title" aria-busy={loading}>
      <div class="section-title">
        <p class="kicker">01 / register</p>
        <h2 id="register-title">Accounts on file <sup>{customers.length}</sup></h2>
      </div>

      {#if !signedIn}
        <div class="empty-state"><span>↗</span><h3>Identity required.</h3><p>Health is public. The customer register opens after a bearer sign-in.</p></div>
      {:else if loading}
        <div class="loading-lines" aria-label="Loading customers"><i></i><i></i><i></i></div>
      {:else if customers.length === 0}
        <div class="empty-state"><span>∅</span><h3>The ledger is clear.</h3><p>Make the first customer entry at right.</p></div>
      {:else}
        <div class="table-wrap">
          <table>
            <thead><tr><th>Customer</th><th>Status</th><th>Owner</th><th>Annual revenue</th></tr></thead>
            <tbody>
              {#each customers as customer (customer.id)}
                <tr>
                  <td><strong>{customer.data.name}</strong><small>{customer.id}</small></td>
                  <td><span class:paused={customer.data.status === "paused"} class="badge">{customer.data.status}</span></td>
                  <td>{customer.data.owner}</td>
                  <td class="revenue">{money(customer.data.annual_revenue)}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </section>

    <aside class="entry-form entry entry-four" aria-labelledby="entry-title">
      {#if signedIn}
        <p class="kicker">02 / new entry</p>
        <h2 id="entry-title">Add a customer</h2>
        <p class="form-intro">Each post carries a fresh idempotency key, so a retry stays one entry.</p>
        <form onsubmit={(event) => { event.preventDefault(); void createCustomer(); }}>
          <label>Name <input bind:value={name} autocomplete="organization" required placeholder="Acme Supply Co." /></label>
          <label>Status <select bind:value={status}><option value="active">Active</option><option value="paused">Paused</option></select></label>
          <label>Owner <input bind:value={owner} autocomplete="name" /></label>
          <label>Annual revenue <span class="input-affix">USD</span><input bind:value={annualRevenue} inputmode="decimal" placeholder="0.00" /></label>
          <button class="post" type="submit" disabled={submitting}>{submitting ? "Posting entry…" : "Post to ledger"} <span aria-hidden="true">→</span></button>
        </form>
      {:else}
        <p class="kicker">02 / access</p>
        <h2 id="entry-title">Sign in</h2>
        <p class="form-intro">Use a Framekit account to read and post customer records. Credentials stay in this form only.</p>
        <form onsubmit={(event) => { event.preventDefault(); void signIn(); }}>
          <label>Email <input bind:value={email} type="email" autocomplete="username" required /></label>
          <label>Password <input bind:value={password} type="password" autocomplete="current-password" required /></label>
          <button class="post" type="submit" disabled={authenticating}>{authenticating ? "Signing in…" : "Open ledger"} <span aria-hidden="true">→</span></button>
        </form>
      {/if}
    </aside>
  </div>

  <footer><span>Framekit SDK v2</span><span>Customer doctype / direct API example</span></footer>
</main>

// examples/frontends/solid/src/App.tsx
import { For, Show, createSignal, onCleanup, onMount } from "solid-js";
import { FramekitSdkError, type HealthResponse } from "@framekit/sdk";
import { clearClientSession, client, framekitApp } from "./api";

type Customer = {
  name?: string;
  status?: string;
  owner?: string;
  annual_revenue?: string;
};

type FormValues = Required<Customer>;
type CustomerRecord = { id: string; data: Customer };
type RequestGuard = { generation: number; controller: AbortController };

const initialForm: FormValues = { name: "", status: "active", owner: "", annual_revenue: "0.00" };

function messageFor(error: unknown): string {
  if (error instanceof FramekitSdkError) {
    const request = error.requestId ? ` Request: ${error.requestId}.` : "";
    return `${error.code}${error.status ? ` (${error.status})` : ""}: ${error.message}.${request}`;
  }
  return error instanceof Error ? error.message : "An unexpected error occurred.";
}

function idempotencyKey(): string {
  return globalThis.crypto?.randomUUID?.() ?? `solid-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function revenue(value: string | undefined): string {
  const amount = Number(value);
  return Number.isFinite(amount) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount) : "—";
}

export function App() {
  const [customers, setCustomers] = createSignal<CustomerRecord[]>([]);
  const [health, setHealth] = createSignal<HealthResponse>();
  const [metadata, setMetadata] = createSignal<unknown>();
  const [loading, setLoading] = createSignal(true);
  const [authenticated, setAuthenticated] = createSignal(false);
  const [signingIn, setSigningIn] = createSignal(false);
  const [submitting, setSubmitting] = createSignal(false);
  const [error, setError] = createSignal<string>();
  const [success, setSuccess] = createSignal<string>();
  const [form, setForm] = createSignal<FormValues>(initialForm);
  const [email, setEmail] = createSignal("admin@example.com");
  const [password, setPassword] = createSignal("");
  let mounted = true;
  let sessionGeneration = 0;
  const activeControllers = new Set<AbortController>();

  const beginRequest = (): RequestGuard => {
    const controller = new AbortController();
    activeControllers.add(controller);
    return { generation: sessionGeneration, controller };
  };

  const finishRequest = (request: RequestGuard): void => {
    activeControllers.delete(request.controller);
  };

  const isCurrent = (request: RequestGuard): boolean => mounted && request.generation === sessionGeneration && !request.controller.signal.aborted;

  const invalidateSession = (): void => {
    sessionGeneration += 1;
    for (const controller of activeControllers) controller.abort();
    activeControllers.clear();
  };

  const checkHealth = async () => {
    const request = beginRequest();
    setLoading(true);
    try {
      const nextHealth = await client.health({ signal: request.controller.signal });
      if (isCurrent(request)) setHealth(nextHealth);
    } catch (cause) {
      if (isCurrent(request)) setError(messageFor(cause));
    } finally {
      if (isCurrent(request)) setLoading(false);
      finishRequest(request);
    }
  };

  const load = async () => {
    if (!authenticated()) return;
    const request = beginRequest();
    setLoading(true);
    setError(undefined);
    try {
      const [nextMetadata, page] = await Promise.all([
        client.meta(),
        client.listPage<Customer>("customer", { limit: 25, sort: { field: "name", direction: "asc" }, signal: request.controller.signal })
      ]);
      if (isCurrent(request)) {
        setMetadata(nextMetadata);
        setCustomers(page.items);
      }
    } catch (cause) {
      if (isCurrent(request)) setError(messageFor(cause));
    } finally {
      if (isCurrent(request)) setLoading(false);
      finishRequest(request);
    }
  };

  const signIn = async (event: SubmitEvent) => {
    event.preventDefault();
    invalidateSession();
    const request = beginRequest();
    setSigningIn(true);
    setError(undefined);
    try {
      await client.login(email(), password());
      if (!isCurrent(request)) return;
      setAuthenticated(true);
      setPassword("");
      setSuccess("Signed in. Customer records are ready.");
      setSigningIn(false);
      void load();
    } catch (cause) {
      if (isCurrent(request)) {
        setError(messageFor(cause));
        setSigningIn(false);
      }
    } finally {
      finishRequest(request);
    }
  };

  const signOut = async () => {
    const logoutClient = client;
    invalidateSession();
    const logoutGeneration = sessionGeneration;
    clearClientSession();
    setError(undefined);
    setAuthenticated(false);
    setCustomers([]);
    setMetadata(undefined);
    setSuccess(undefined);
    setLoading(false);
    setSigningIn(false);
    setSubmitting(false);
    try {
      await logoutClient.logout();
    } catch (cause) {
      if (mounted && sessionGeneration === logoutGeneration) setError(messageFor(cause));
    } finally {
      // The active client was replaced before logout so late responses cannot revive a session.
    }
  };

  const createCustomer = async (event: SubmitEvent) => {
    event.preventDefault();
    const request = beginRequest();
    setSubmitting(true);
    setError(undefined);
    setSuccess(undefined);
    try {
      const value = form();
      const customer = await client.create<Customer>("customer", value, { idempotencyKey: idempotencyKey(), signal: request.controller.signal });
      if (isCurrent(request)) {
        setCustomers((current) => [customer, ...current]);
        setForm(initialForm);
        setSuccess(`${customer.data.name || "Customer"} added to the ledger.`);
      }
    } catch (cause) {
      if (isCurrent(request)) setError(messageFor(cause));
    } finally {
      if (isCurrent(request)) setSubmitting(false);
      finishRequest(request);
    }
  };

  onMount(() => {
    void checkHealth();
    onCleanup(() => {
      mounted = false;
      invalidateSession();
    });
  });

  return <main class="ledger-shell">
    <header class="masthead">
      <p class="eyebrow">Framekit / {framekitApp}</p>
      <h1>Customer<br /><em>ledger</em></h1>
      <div class="system-note" aria-live="polite">
        <span class={health()?.ok ? "status-dot online" : "status-dot"} />
        <span>{health()?.ok ? `${health()!.app} responding` : loading() ? "checking system" : "connection unknown"}</span>
      </div>
    </header>

    <section class="intro" aria-label="Ledger overview">
      <p>New accounts, kept in plain sight. Live data from the Framekit API—not a stored session.</p>
      <Show when={authenticated()} fallback={<span class="signin-prompt">Sign in to open the ledger</span>}>
        <div class="actions"><button class="text-button" type="button" onClick={load} disabled={loading()}>{loading() ? "Refreshing…" : "Refresh ledger"}</button><button class="text-button" type="button" onClick={signOut}>Sign out</button></div>
      </Show>
    </section>

    <Show when={error()}>{(value) => <p class="notice error" role="alert">{value()}</p>}</Show>
    <Show when={success()}>{(value) => <p class="notice success" role="status">{value()}</p>}</Show>

    <Show when={authenticated()} fallback={<section class="signin-panel" aria-labelledby="signin-title">
      <div><p class="eyebrow">Account access</p><h2 id="signin-title">Open the<br /><em>ledger</em></h2><p>Use a Framekit account to retrieve protected customer records. Your bearer token stays only in this page’s memory.</p></div>
      <form class="signin-form" onSubmit={signIn}>
        <label>Email <input required type="email" autocomplete="email" value={email()} onInput={(event) => setEmail(event.currentTarget.value)} /></label>
        <label>Password <input required type="password" autocomplete="current-password" value={password()} onInput={(event) => setPassword(event.currentTarget.value)} /></label>
        <button class="submit-button" type="submit" disabled={signingIn()}>{signingIn() ? "Signing in…" : "Sign in"}</button>
      </form>
    </section>}>
    <section class="ledger-grid">
      <form class="new-entry" onSubmit={createCustomer}>
        <div class="section-heading"><span>01</span><h2>New entry</h2></div>
        <label>Name <input required value={form().name} onInput={(event) => setForm({ ...form(), name: event.currentTarget.value })} placeholder="Northstar Studio" /></label>
        <label>Status <select value={form().status} onChange={(event) => setForm({ ...form(), status: event.currentTarget.value })}><option value="active">Active</option><option value="paused">Paused</option></select></label>
        <label>Owner <input required value={form().owner} onInput={(event) => setForm({ ...form(), owner: event.currentTarget.value })} placeholder="Avery Chen" /></label>
        <label>Annual revenue <input required inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" value={form().annual_revenue} onInput={(event) => setForm({ ...form(), annual_revenue: event.currentTarget.value })} /></label>
        <button class="submit-button" type="submit" disabled={submitting()}>{submitting() ? "Recording…" : "Record customer"}</button>
        <p class="form-note">Each submission includes a fresh idempotency key.</p>
      </form>

      <section class="entries" aria-busy={loading()}>
        <div class="section-heading"><span>02</span><h2>Accounts on record</h2><span class="count">{customers().length}</span></div>
        <Show when={!loading()} fallback={<p class="state">Loading customer records…</p>}>
          <Show when={customers().length > 0} fallback={<p class="state">No customers yet. Make the first entry.</p>}>
            <div class="table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Owner</th><th>Annual revenue</th></tr></thead><tbody><For each={customers()}>{(customer) => <tr><td><strong>{customer.data.name || "Untitled"}</strong><small>{customer.id}</small></td><td><span class="pill">{customer.data.status || "—"}</span></td><td>{customer.data.owner || "—"}</td><td class="money">{revenue(customer.data.annual_revenue)}</td></tr>}</For></tbody></table></div>
          </Show>
        </Show>
      </section>
    </section>
    </Show>

    <footer><span>Metadata {metadata() ? "loaded" : "pending"}</span><span>v2 client · default tenant</span></footer>
  </main>;
}
