// examples/frontends/react/src/App.tsx
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { FramekitClient, FramekitSdkError, type HealthResponse } from "@framekit/sdk";

type CustomerData = {
  name?: string;
  status?: "active" | "paused" | string;
  owner?: string;
  annual_revenue?: string | number;
};

type Customer = { id: string; revision: number; data: CustomerData };
type CustomerForm = { name: string; status: "active" | "paused"; owner: string; annual_revenue: string };
type LedgerMeta = { name?: string; modules?: Array<{ doctypes?: unknown[] }> };

const apiUrl = import.meta.env.VITE_FRAMEKIT_API_URL?.replace(/\/$/, "") ?? "";
const emptyForm: CustomerForm = { name: "", status: "active", owner: "Sales", annual_revenue: "0.00" };

function createClient() {
  return new FramekitClient({
    version: 2,
    baseUrl: apiUrl,
    authMode: "bearer",
    tenant: { tenantId: "default", userId: "administrator", roles: ["administrator"], permissions: ["*"] }
  });
}

export function App() {
  const clientRef = useRef(createClient());
  const generationRef = useRef(0);
  const listControllerRef = useRef<AbortController | undefined>(undefined);
  const mountedRef = useRef(true);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [health, setHealth] = useState<HealthResponse>();
  const [meta, setMeta] = useState<LedgerMeta>();
  const [healthLoading, setHealthLoading] = useState(true);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [signingIn, setSigningIn] = useState(false);
  const [signedIn, setSignedIn] = useState(false);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<unknown>();
  const [form, setForm] = useState<CustomerForm>(emptyForm);

  const isCurrent = useCallback((generation: number, client: FramekitClient) => (
    mountedRef.current && generationRef.current === generation && clientRef.current === client
  ), []);

  const loadLedger = useCallback(async (client: FramekitClient, generation: number) => {
    listControllerRef.current?.abort();
    const controller = new AbortController();
    listControllerRef.current = controller;
    if (!isCurrent(generation, client)) return;
    setLoading(true);
    setError(undefined);
    try {
      const [nextMeta, page] = await Promise.all([
        client.meta<LedgerMeta>(),
        client.listPage<CustomerData>("customer", { limit: 20, signal: controller.signal })
      ]);
      if (isCurrent(generation, client) && !controller.signal.aborted) {
        setMeta(nextMeta);
        setCustomers(page.items);
      }
    } catch (failure) {
      if (isCurrent(generation, client) && !controller.signal.aborted) setError(failure);
    } finally {
      if (isCurrent(generation, client) && !controller.signal.aborted) {
        setLoading(false);
        setRefreshing(false);
      }
    }
  }, [isCurrent]);

  useEffect(() => {
    mountedRef.current = true;
    const controller = new AbortController();
    const client = clientRef.current;
    void client.health({ signal: controller.signal }).then((nextHealth) => {
      if (mountedRef.current && clientRef.current === client) setHealth(nextHealth);
    }).catch((failure: unknown) => {
      if (mountedRef.current && !controller.signal.aborted && clientRef.current === client) setError(failure);
    }).finally(() => {
      if (mountedRef.current && !controller.signal.aborted && clientRef.current === client) setHealthLoading(false);
    });
    return () => {
      mountedRef.current = false;
      controller.abort();
      listControllerRef.current?.abort();
      generationRef.current += 1;
    };
  }, []);

  const refresh = () => {
    const client = clientRef.current;
    const generation = generationRef.current;
    setRefreshing(true);
    void loadLedger(client, generation);
  };

  const signIn = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const email = String(data.get("email") ?? "");
    const password = String(data.get("password") ?? "");
    listControllerRef.current?.abort();
    const generation = generationRef.current + 1;
    generationRef.current = generation;
    const client = createClient();
    clientRef.current = client;
    setSigningIn(true);
    setError(undefined);
    try {
      await client.login(email, password);
      if (!isCurrent(generation, client)) return;
      setSignedIn(true);
      await loadLedger(client, generation);
    } catch (failure) {
      if (isCurrent(generation, client)) setError(failure);
    } finally {
      if (isCurrent(generation, client)) setSigningIn(false);
    }
  };

  const logout = async () => {
    const client = clientRef.current;
    listControllerRef.current?.abort();
    const generation = generationRef.current + 1;
    generationRef.current = generation;
    try {
      await client.logout();
    } catch (failure) {
      if (mountedRef.current && generationRef.current === generation) setError(failure);
    } finally {
      if (generationRef.current !== generation) return;
      clientRef.current = createClient();
      if (mountedRef.current) {
        setSignedIn(false);
        setCustomers([]);
        setMeta(undefined);
        setForm(emptyForm);
        setLoading(false);
        setRefreshing(false);
        setCreating(false);
      }
    }
  };

  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const client = clientRef.current;
    const generation = generationRef.current;
    setCreating(true);
    setError(undefined);
    try {
      await client.create<CustomerData>("customer", {
        name: form.name.trim(), status: form.status, owner: form.owner.trim(), annual_revenue: form.annual_revenue
      }, { idempotencyKey: crypto.randomUUID() });
      if (!isCurrent(generation, client)) return;
      setForm(emptyForm);
      await loadLedger(client, generation);
    } catch (failure) {
      if (isCurrent(generation, client)) setError(failure);
    } finally {
      if (isCurrent(generation, client)) setCreating(false);
    }
  };

  const appName = meta?.name ?? health?.app ?? "Framekit";
  const doctypeCount = meta?.modules?.flatMap((module) => module.doctypes ?? []).length ?? 0;
  const detail = useMemo(() => describeError(error), [error]);

  return <main className="ledger-shell">
    <header className="masthead enter">
      <p className="eyebrow">{appName} / customer registry</p>
      <div className="masthead-row">
        <h1>Field<br /><em>Ledger</em></h1>
        <div className="system-stamp" aria-label={health ? "API health: online" : "API health: checking"}>
          <span className={health ? "pulse online" : "pulse"} />
          <span>{health ? "live / verified" : healthLoading ? "live / checking" : "live / unavailable"}</span>
          <small>{apiUrl || "same-origin API proxy"}</small>
        </div>
      </div>
    </header>

    <section className="ledger-grid">
      <aside className="margin-note enter delay-1">
        <p>Register companies, record stewardship, and keep a small, legible account of the work ahead.</p>
        <dl>
          <div><dt>Tenant</dt><dd>default</dd></div>
          <div><dt>Doctype</dt><dd>customer</dd></div>
          <div><dt>Schema</dt><dd>{doctypeCount || "—"} entries</dd></div>
        </dl>
      </aside>

      <section className="records enter delay-2" aria-labelledby="records-title">
        <div className="section-heading">
          <div><p className="eyebrow">folio 01</p><h2 id="records-title">Customer register</h2></div>
          {signedIn && <div className="action-pair"><button className="text-button" onClick={refresh} disabled={loading || refreshing}>
              {refreshing ? "Refreshing…" : "Refresh list"}
            </button><button className="text-button" onClick={() => void logout()}>Sign out</button></div>}
        </div>

        {detail && <ErrorNotice detail={detail} />}
        {!signedIn && <p className="state-message">Sign in to read and add customer records. Your session remains only in this browser tab’s memory.</p>}
        {signedIn && loading && <p className="state-message" role="status">Opening the register…</p>}
        {signedIn && !loading && !detail && customers.length === 0 && <p className="state-message">No customers entered yet. The first line is waiting.</p>}
        {signedIn && !loading && !detail && customers.length > 0 && <div className="table-wrap">
          <table><thead><tr><th>Name</th><th>Status</th><th>Owner</th><th>Annual revenue</th></tr></thead>
            <tbody>{customers.map((customer) => <tr key={customer.id}>
              <td><strong>{customer.data.name ?? "Untitled"}</strong><small>{customer.id}</small></td>
              <td><span className={`status ${customer.data.status === "active" ? "active" : "paused"}`}>{customer.data.status ?? "—"}</span></td>
              <td>{customer.data.owner ?? "—"}</td><td>{formatRevenue(customer.data.annual_revenue)}</td>
            </tr>)}</tbody>
          </table>
        </div>}
      </section>

      <section className="entry-form enter delay-3" aria-labelledby="entry-title">
        <p className="eyebrow">folio 02 / {signedIn ? "new line" : "access"}</p><h2 id="entry-title">{signedIn ? "Enter a customer" : "Sign in"}</h2>
        {!signedIn ? <form key="sign-in" onSubmit={signIn}>
          <label>Email <input name="email" type="email" autoComplete="username" defaultValue="admin@example.com" required /></label>
          <label>Password <input name="password" type="password" autoComplete="current-password" required /></label>
          <button className="submit-button" disabled={signingIn}>{signingIn ? "Signing in…" : "Open ledger"}</button>
        </form> : <form key="customer-entry" onSubmit={submit}>
          <label>Name <input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label>
          <div className="form-pair"><label>Status <select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as CustomerForm["status"] })}><option value="active">Active</option><option value="paused">Paused</option></select></label>
            <label>Owner <input required value={form.owner} onChange={(e) => setForm({ ...form, owner: e.target.value })} /></label></div>
          <label>Annual revenue <input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" value={form.annual_revenue} onChange={(e) => setForm({ ...form, annual_revenue: e.target.value })} /></label>
          <button className="submit-button" disabled={creating}>{creating ? "Entering…" : "Add to ledger"}</button>
        </form>}
      </section>
    </section>
  </main>;
}

function ErrorNotice({ detail }: { detail: string }) {
  return <div className="error-notice" role="alert"><strong>Request recorded as incomplete.</strong><span>{detail}</span></div>;
}

function describeError(error: unknown): string | undefined {
  if (error === undefined || error === null) return undefined;
  if (error instanceof FramekitSdkError) {
    return `${error.name} · ${error.code}${error.status ? ` · HTTP ${error.status}` : ""}${error.requestId ? ` · request ${error.requestId}` : ""}: ${error.message}`;
  }
  return error instanceof Error ? error.message : "An unknown error interrupted the request.";
}

function formatRevenue(value: CustomerData["annual_revenue"]): string {
  const number = typeof value === "number" ? value : Number(value);
  return Number.isFinite(number) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(number) : "—";
}

// examples/frontends/svelte/src/App.svelte
<script lang="ts">
  import {
    FramekitAuthenticationError,
    FramekitAuthorizationError,
    FramekitConflictError,
    FramekitSdkError,
    FramekitServerError,
    FramekitTransportError,
    FramekitValidationError,
    FramekitClient
  } from "@framekit/sdk";
  import { onDestroy, onMount } from "svelte";

  type CustomerData = {
    name: string;
    status: "active" | "paused";
    owner: string;
    annual_revenue: string;
  };

  type CustomerRecord = {
    id: string;
    data: CustomerData;
  };

  type MetaSnapshot = { app?: { name?: string; version?: string }; name?: string; version?: string };

  const apiUrl = import.meta.env.VITE_FRAMEKIT_API_URL ?? "";
  const tenantId = import.meta.env.VITE_FRAMEKIT_TENANT_ID ?? "default";
  const appName = import.meta.env.VITE_FRAMEKIT_APP_NAME ?? "CRM";
  const userId = import.meta.env.VITE_FRAMEKIT_USER_ID ?? "frontend";
  function createClient() {
    return new FramekitClient({
      version: 2,
      baseUrl: apiUrl,
      authMode: "bearer",
      tenant: { tenantId, userId, roles: ["administrator"], permissions: ["*"] }
    });
  }

  let client = createClient();
  let sessionGeneration = 0;
  let mounted = true;
  let refreshController: AbortController | null = null;
  let createController: AbortController | null = null;

  let customers = $state<CustomerRecord[]>([]);
  let health = $state<"checking" | "online" | "offline">("checking");
  let meta = $state<MetaSnapshot | null>(null);
  let loading = $state(false);
  let submitting = $state(false);
  let authenticating = $state(false);
  let signedIn = $state(false);
  let error = $state<string | null>(null);
  let notice = $state<string | null>(null);
  let name = $state("");
  let status = $state<CustomerData["status"]>("active");
  let owner = $state("Sales");
  let annualRevenue = $state("0.00");
  let email = $state("admin@example.com");
  let password = $state("");

  onMount(() => {
    void checkHealth();
  });

  onDestroy(() => {
    mounted = false;
    invalidateSession();
  });

  function abortProtectedRequests() {
    refreshController?.abort();
    createController?.abort();
    refreshController = null;
    createController = null;
  }

  function invalidateSession() {
    sessionGeneration += 1;
    abortProtectedRequests();
  }

  function isCurrent(generation: number, requestClient: FramekitClient) {
    return mounted && generation === sessionGeneration && client === requestClient;
  }

  async function checkHealth() {
    const generation = sessionGeneration;
    const requestClient = client;
    health = "checking";
    try {
      const healthResponse = await requestClient.health();
      if (!isCurrent(generation, requestClient)) return;
      health = healthResponse.ok ? "online" : "offline";
    } catch (cause) {
      if (!isCurrent(generation, requestClient)) return;
      health = "offline";
      error = presentError(cause);
    }
  }

  async function refresh() {
    if (!signedIn) return;
    refreshController?.abort();
    const controller = new AbortController();
    refreshController = controller;
    const generation = sessionGeneration;
    const requestClient = client;
    loading = true;
    error = null;
    notice = null;
    try {
      const [metaResponse, page] = await Promise.all([
        requestClient.meta<MetaSnapshot>(),
        requestClient.listPage<CustomerData>("customer", { limit: 50, sort: { field: "name", direction: "asc" }, signal: controller.signal })
      ]);
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      meta = metaResponse;
      customers = page.items;
    } catch (cause) {
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, requestClient) && refreshController === controller) {
        refreshController = null;
        loading = false;
      }
    }
  }

  async function signIn() {
    invalidateSession();
    const generation = sessionGeneration;
    const loginClient = createClient();
    client = loginClient;
    authenticating = true;
    error = null;
    notice = null;
    try {
      await loginClient.login(email, password);
      if (!isCurrent(generation, loginClient)) return;
      password = "";
      signedIn = true;
      notice = "Signed in. Loading the customer ledger.";
      await refresh();
    } catch (cause) {
      if (!isCurrent(generation, loginClient)) return;
      password = "";
      signedIn = false;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, loginClient)) authenticating = false;
    }
  }

  async function signOut() {
    const logoutClient = client;
    invalidateSession();
    error = null;
    notice = null;
    try {
      await logoutClient.logout();
      if (mounted) notice = "Signed out. Your session was cleared from memory.";
    } catch (cause) {
      if (mounted) error = presentError(cause);
    } finally {
      client = createClient();
      if (!mounted) return;
      signedIn = false;
      customers = [];
      meta = null;
      password = "";
      loading = false;
      submitting = false;
    }
  }

  async function createCustomer() {
    if (!name.trim()) {
      error = "A customer name is required before an entry can be posted.";
      return;
    }
    createController?.abort();
    const controller = new AbortController();
    createController = controller;
    const generation = sessionGeneration;
    const requestClient = client;
    submitting = true;
    error = null;
    notice = null;
    const idempotencyKey = crypto.randomUUID();
    try {
      const customer = await requestClient.create<CustomerData>("customer", {
        name: name.trim(),
        status,
        owner: owner.trim() || "Sales",
        annual_revenue: annualRevenue.trim() || "0.00"
      }, { idempotencyKey, signal: controller.signal });
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      customers = [customer, ...customers];
      name = "";
      status = "active";
      owner = "Sales";
      annualRevenue = "0.00";
      notice = `Entry ${customer.id} posted to the ledger.`;
    } catch (cause) {
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, requestClient) && createController === controller) {
        createController = null;
        submitting = false;
      }
    }
  }

  function presentError(cause: unknown): string {
    if (cause instanceof FramekitValidationError) return `Validation (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitAuthenticationError) return `Authentication (${cause.status ?? "no status"}): ${cause.message}`;
    if (cause instanceof FramekitAuthorizationError) return `Permission denied (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitConflictError) return `Conflict (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitServerError) return `Server error (${cause.status ?? "unknown"}): ${cause.message}`;
    if (cause instanceof FramekitTransportError) return `Connection failed: ${cause.message}`;
    if (cause instanceof FramekitSdkError) return `Framekit ${cause.code}: ${cause.message}`;
    return cause instanceof Error ? cause.message : "An unexpected error interrupted the request.";
  }

  function money(value: unknown): string {
    const amount = Number(value);
    return Number.isFinite(amount) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount) : "—";
  }
</script>

<svelte:head><title>Customer Ledger · {appName}</title></svelte:head>

<main class="ledger-shell">
  <header class="masthead entry entry-one">
    <p class="kicker"><span class="signal" aria-hidden="true"></span> Framekit / {appName}</p>
    <div class="masthead-row">
      <h1>Customer<br /><em>ledger.</em></h1>
      <div class="terminal" aria-label="Connection details">
        <span class:online={health === "online"} class:offline={health === "offline"} class="status-dot"></span>
        <span>{health === "checking" ? "checking node" : health === "online" ? "node live" : "node unavailable"}</span>
        <small>{apiUrl || "same-origin API proxy"}</small>
      </div>
    </div>
  </header>

  <section class="context entry entry-two" aria-label="Ledger context">
    <p>Tenant <strong>{tenantId}</strong> / operator <strong>{userId}</strong></p>
    <p>{meta?.app?.name ?? meta?.name ?? appName}{meta?.app?.version ?? meta?.version ? ` · ${meta.app?.version ?? meta.version}` : ""}</p>
    {#if signedIn}
      <div class="context-actions">
        <button class="refresh" onclick={refresh} disabled={loading} aria-label="Refresh customer ledger"><span aria-hidden="true">↻</span> {loading ? "Refreshing" : "Refresh"}</button>
        <button class="refresh" onclick={() => void signOut()} aria-label="Sign out">Sign out</button>
      </div>
    {:else}
      <span class="auth-prompt">Sign in to open ledger</span>
    {/if}
  </section>

  {#if error}
    <div class="message error" role="alert"><b>Request note</b><span>{error}</span></div>
  {/if}
  {#if notice}
    <div class="message success" role="status"><b>Posted</b><span>{notice}</span></div>
  {/if}

  <div class="ledger-grid">
    <section class="register entry entry-three" aria-labelledby="register-title" aria-busy={loading}>
      <div class="section-title">
        <p class="kicker">01 / register</p>
        <h2 id="register-title">Accounts on file <sup>{customers.length}</sup></h2>
      </div>

      {#if !signedIn}
        <div class="empty-state"><span>↗</span><h3>Identity required.</h3><p>Health is public. The customer register opens after a bearer sign-in.</p></div>
      {:else if loading}
        <div class="loading-lines" aria-label="Loading customers"><i></i><i></i><i></i></div>
      {:else if customers.length === 0}
        <div class="empty-state"><span>∅</span><h3>The ledger is clear.</h3><p>Make the first customer entry at right.</p></div>
      {:else}
        <div class="table-wrap">
          <table>
            <thead><tr><th>Customer</th><th>Status</th><th>Owner</th><th>Annual revenue</th></tr></thead>
            <tbody>
              {#each customers as customer (customer.id)}
                <tr>
                  <td><strong>{customer.data.name}</strong><small>{customer.id}</small></td>
                  <td><span class:paused={customer.data.status === "paused"} class="badge">{customer.data.status}</span></td>
                  <td>{customer.data.owner}</td>
                  <td class="revenue">{money(customer.data.annual_revenue)}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </section>

    <aside class="entry-form entry entry-four" aria-labelledby="entry-title">
      {#if signedIn}
        <p class="kicker">02 / new entry</p>
        <h2 id="entry-title">Add a customer</h2>
        <p class="form-intro">Each post carries a fresh idempotency key, so a retry stays one entry.</p>
        <form onsubmit={(event) => { event.preventDefault(); void createCustomer(); }}>
          <label>Name <input bind:value={name} autocomplete="organization" required placeholder="Acme Supply Co." /></label>
          <label>Status <select bind:value={status}><option value="active">Active</option><option value="paused">Paused</option></select></label>
          <label>Owner <input bind:value={owner} autocomplete="name" /></label>
          <label>Annual revenue <span class="input-affix">USD</span><input bind:value={annualRevenue} inputmode="decimal" placeholder="0.00" /></label>
          <button class="post" type="submit" disabled={submitting}>{submitting ? "Posting entry…" : "Post to ledger"} <span aria-hidden="true">→</span></button>
        </form>
      {:else}
        <p class="kicker">02 / access</p>
        <h2 id="entry-title">Sign in</h2>
        <p class="form-intro">Use a Framekit account to read and post customer records. Credentials stay in this form only.</p>
        <form onsubmit={(event) => { event.preventDefault(); void signIn(); }}>
          <label>Email <input bind:value={email} type="email" autocomplete="username" required /></label>
          <label>Password <input bind:value={password} type="password" autocomplete="current-password" required /></label>
          <button class="post" type="submit" disabled={authenticating}>{authenticating ? "Signing in…" : "Open ledger"} <span aria-hidden="true">→</span></button>
        </form>
      {/if}
    </aside>
  </div>

  <footer><span>Framekit SDK v2</span><span>Customer doctype / direct API example</span></footer>
</main>
