// examples/frontends/vue/src/components/LedgerHeader.vue
<script setup lang="ts">
defineProps<{ alive?: boolean; baseUrl: string }>();
</script>

<template>
  <header class="masthead entry entry-one">
    <div><p class="eyebrow">FRAMEKIT / CUSTOMER REGISTER</p><h1>Field<br /><em>ledger.</em></h1></div>
    <div class="masthead-note" aria-label="Connection details">
      <span class="status-dot" :class="{ alive }" aria-hidden="true"></span>
      <span>{{ alive ? "live connection" : "awaiting connection" }}</span>
      <code>{{ baseUrl || "same-origin API proxy" }}</code>
    </div>
  </header>
</template>

// examples/frontends/solid/src/components/LedgerHeader.tsx
import type { Accessor } from "solid-js";
import type { HealthResponse } from "@framekit/sdk";
import { framekitApp } from "../lib/api/framekit";

type LedgerHeaderProps = { health: Accessor<HealthResponse | undefined>; loading: Accessor<boolean> };

export function LedgerHeader(props: LedgerHeaderProps) {
  return <header class="masthead">
    <p class="eyebrow">Framekit / {framekitApp}</p>
    <h1>Customer<br /><em>ledger</em></h1>
    <div class="system-note" aria-live="polite">
      <span class={props.health()?.ok ? "status-dot online" : "status-dot"} />
      <span>{props.health()?.ok ? `${props.health()!.app} responding` : props.loading() ? "checking system" : "connection unknown"}</span>
    </div>
  </header>;
}
