// examples/frontends/vue/src/components/SignInForm.vue
<script setup lang="ts">
import type { UnwrapNestedRefs } from "vue";
defineProps<{ credentials: UnwrapNestedRefs<{ email: string; password: string }>; authenticating: boolean; loading: boolean }>();
const emit = defineEmits<{ submit: [] }>();
</script>

<template>
  <section class="intake-panel entry entry-four" aria-labelledby="sign-in-title"><p class="eyebrow">02 / ACCESS SLIP</p><h2 id="sign-in-title">Sign in</h2>
    <form @submit.prevent="emit('submit')"><label><span>Email</span><input v-model.trim="credentials.email" type="email" required autocomplete="username" /></label>
      <label><span>Password</span><input v-model="credentials.password" type="password" required autocomplete="current-password" /></label>
      <button class="submit-button" type="submit" :disabled="authenticating || loading"><span>{{ authenticating ? "Opening…" : "Open ledger" }}</span><b aria-hidden="true">↗</b></button>
    </form><p class="idempotency-note">Session credentials remain only in this browser tab’s memory.</p>
  </section>
</template>

// examples/frontends/solid/src/components/SignInForm.tsx
import type { Accessor } from "solid-js";

type SignInFormProps = {
  email: Accessor<string>;
  password: Accessor<string>;
  signingIn: Accessor<boolean>;
  setEmail: (value: string) => void;
  setPassword: (value: string) => void;
  onSubmit: (event: SubmitEvent) => Promise<void>;
};

export function SignInForm(props: SignInFormProps) {
  return <section class="signin-panel" aria-labelledby="signin-title">
    <div><p class="eyebrow">Account access</p><h2 id="signin-title">Open the<br /><em>ledger</em></h2><p>Use a Framekit account to retrieve protected customer records. Your bearer token stays only in this page’s memory.</p></div>
    <form class="signin-form" onSubmit={props.onSubmit}>
      <label>Email <input required type="email" autocomplete="email" value={props.email()} onInput={(event) => props.setEmail(event.currentTarget.value)} /></label>
      <label>Password <input required type="password" autocomplete="current-password" value={props.password()} onInput={(event) => props.setPassword(event.currentTarget.value)} /></label>
      <button class="submit-button" type="submit" disabled={props.signingIn()}>{props.signingIn() ? "Signing in…" : "Sign in"}</button>
    </form>
  </section>;
}
