// examples/frontends/svelte/src/App.svelte
<script lang="ts">
  import {
    FramekitAuthenticationError,
    FramekitAuthorizationError,
    FramekitConflictError,
    FramekitSdkError,
    FramekitServerError,
    FramekitTransportError,
    FramekitValidationError,
    FramekitClient
  } from "@framekit/sdk";
  import { onDestroy, onMount } from "svelte";

  type CustomerData = {
    name: string;
    status: "active" | "paused";
    owner: string;
    annual_revenue: string;
  };

  type CustomerRecord = {
    id: string;
    data: CustomerData;
  };

  type MetaSnapshot = { app?: { name?: string; version?: string }; name?: string; version?: string };

  const apiUrl = import.meta.env.VITE_FRAMEKIT_API_URL ?? "";
  const tenantId = import.meta.env.VITE_FRAMEKIT_TENANT_ID ?? "default";
  const appName = import.meta.env.VITE_FRAMEKIT_APP_NAME ?? "CRM";
  const userId = import.meta.env.VITE_FRAMEKIT_USER_ID ?? "frontend";
  function createClient() {
    return new FramekitClient({
      version: 2,
      baseUrl: apiUrl,
      authMode: "bearer",
      tenant: { tenantId, userId, roles: ["administrator"], permissions: ["*"] }
    });
  }

  let client = createClient();
  let sessionGeneration = 0;
  let mounted = true;
  let refreshController: AbortController | null = null;
  let createController: AbortController | null = null;

  let customers = $state<CustomerRecord[]>([]);
  let health = $state<"checking" | "online" | "offline">("checking");
  let meta = $state<MetaSnapshot | null>(null);
  let loading = $state(false);
  let submitting = $state(false);
  let authenticating = $state(false);
  let signedIn = $state(false);
  let error = $state<string | null>(null);
  let notice = $state<string | null>(null);
  let name = $state("");
  let status = $state<CustomerData["status"]>("active");
  let owner = $state("Sales");
  let annualRevenue = $state("0.00");
  let email = $state("admin@example.com");
  let password = $state("");

  onMount(() => {
    void checkHealth();
  });

  onDestroy(() => {
    mounted = false;
    invalidateSession();
  });

  function abortProtectedRequests() {
    refreshController?.abort();
    createController?.abort();
    refreshController = null;
    createController = null;
  }

  function invalidateSession() {
    sessionGeneration += 1;
    abortProtectedRequests();
  }

  function isCurrent(generation: number, requestClient: FramekitClient) {
    return mounted && generation === sessionGeneration && client === requestClient;
  }

  async function checkHealth() {
    const generation = sessionGeneration;
    const requestClient = client;
    health = "checking";
    try {
      const healthResponse = await requestClient.health();
      if (!isCurrent(generation, requestClient)) return;
      health = healthResponse.ok ? "online" : "offline";
    } catch (cause) {
      if (!isCurrent(generation, requestClient)) return;
      health = "offline";
      error = presentError(cause);
    }
  }

  async function refresh() {
    if (!signedIn) return;
    refreshController?.abort();
    const controller = new AbortController();
    refreshController = controller;
    const generation = sessionGeneration;
    const requestClient = client;
    loading = true;
    error = null;
    notice = null;
    try {
      const [metaResponse, page] = await Promise.all([
        requestClient.meta<MetaSnapshot>(),
        requestClient.listPage<CustomerData>("customer", { limit: 50, sort: { field: "name", direction: "asc" }, signal: controller.signal })
      ]);
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      meta = metaResponse;
      customers = page.items;
    } catch (cause) {
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, requestClient) && refreshController === controller) {
        refreshController = null;
        loading = false;
      }
    }
  }

  async function signIn() {
    invalidateSession();
    const generation = sessionGeneration;
    const loginClient = createClient();
    client = loginClient;
    authenticating = true;
    error = null;
    notice = null;
    try {
      await loginClient.login(email, password);
      if (!isCurrent(generation, loginClient)) return;
      password = "";
      signedIn = true;
      notice = "Signed in. Loading the customer ledger.";
      await refresh();
    } catch (cause) {
      if (!isCurrent(generation, loginClient)) return;
      password = "";
      signedIn = false;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, loginClient)) authenticating = false;
    }
  }

  async function signOut() {
    const logoutClient = client;
    invalidateSession();
    error = null;
    notice = null;
    try {
      await logoutClient.logout();
      if (mounted) notice = "Signed out. Your session was cleared from memory.";
    } catch (cause) {
      if (mounted) error = presentError(cause);
    } finally {
      client = createClient();
      if (!mounted) return;
      signedIn = false;
      customers = [];
      meta = null;
      password = "";
      loading = false;
      submitting = false;
    }
  }

  async function createCustomer() {
    if (!name.trim()) {
      error = "A customer name is required before an entry can be posted.";
      return;
    }
    createController?.abort();
    const controller = new AbortController();
    createController = controller;
    const generation = sessionGeneration;
    const requestClient = client;
    submitting = true;
    error = null;
    notice = null;
    const idempotencyKey = crypto.randomUUID();
    try {
      const customer = await requestClient.create<CustomerData>("customer", {
        name: name.trim(),
        status,
        owner: owner.trim() || "Sales",
        annual_revenue: annualRevenue.trim() || "0.00"
      }, { idempotencyKey, signal: controller.signal });
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      customers = [customer, ...customers];
      name = "";
      status = "active";
      owner = "Sales";
      annualRevenue = "0.00";
      notice = `Entry ${customer.id} posted to the ledger.`;
    } catch (cause) {
      if (!isCurrent(generation, requestClient) || controller.signal.aborted) return;
      error = presentError(cause);
    } finally {
      if (isCurrent(generation, requestClient) && createController === controller) {
        createController = null;
        submitting = false;
      }
    }
  }

  function presentError(cause: unknown): string {
    if (cause instanceof FramekitValidationError) return `Validation (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitAuthenticationError) return `Authentication (${cause.status ?? "no status"}): ${cause.message}`;
    if (cause instanceof FramekitAuthorizationError) return `Permission denied (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitConflictError) return `Conflict (${cause.code}): ${cause.message}`;
    if (cause instanceof FramekitServerError) return `Server error (${cause.status ?? "unknown"}): ${cause.message}`;
    if (cause instanceof FramekitTransportError) return `Connection failed: ${cause.message}`;
    if (cause instanceof FramekitSdkError) return `Framekit ${cause.code}: ${cause.message}`;
    return cause instanceof Error ? cause.message : "An unexpected error interrupted the request.";
  }

  function money(value: unknown): string {
    const amount = Number(value);
    return Number.isFinite(amount) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount) : "—";
  }
</script>

<svelte:head><title>Customer Ledger · {appName}</title></svelte:head>

<main class="ledger-shell">
  <header class="masthead entry entry-one">
    <p class="kicker"><span class="signal" aria-hidden="true"></span> Framekit / {appName}</p>
    <div class="masthead-row">
      <h1>Customer<br /><em>ledger.</em></h1>
      <div class="terminal" aria-label="Connection details">
        <span class:online={health === "online"} class:offline={health === "offline"} class="status-dot"></span>
        <span>{health === "checking" ? "checking node" : health === "online" ? "node live" : "node unavailable"}</span>
        <small>{apiUrl || "same-origin API proxy"}</small>
      </div>
    </div>
  </header>

  <section class="context entry entry-two" aria-label="Ledger context">
    <p>Tenant <strong>{tenantId}</strong> / operator <strong>{userId}</strong></p>
    <p>{meta?.app?.name ?? meta?.name ?? appName}{meta?.app?.version ?? meta?.version ? ` · ${meta.app?.version ?? meta.version}` : ""}</p>
    {#if signedIn}
      <div class="context-actions">
        <button class="refresh" onclick={refresh} disabled={loading} aria-label="Refresh customer ledger"><span aria-hidden="true">↻</span> {loading ? "Refreshing" : "Refresh"}</button>
        <button class="refresh" onclick={() => void signOut()} aria-label="Sign out">Sign out</button>
      </div>
    {:else}
      <span class="auth-prompt">Sign in to open ledger</span>
    {/if}
  </section>

  {#if error}
    <div class="message error" role="alert"><b>Request note</b><span>{error}</span></div>
  {/if}
  {#if notice}
    <div class="message success" role="status"><b>Posted</b><span>{notice}</span></div>
  {/if}

  <div class="ledger-grid">
    <section class="register entry entry-three" aria-labelledby="register-title" aria-busy={loading}>
      <div class="section-title">
        <p class="kicker">01 / register</p>
        <h2 id="register-title">Accounts on file <sup>{customers.length}</sup></h2>
      </div>

      {#if !signedIn}
        <div class="empty-state"><span>↗</span><h3>Identity required.</h3><p>Health is public. The customer register opens after a bearer sign-in.</p></div>
      {:else if loading}
        <div class="loading-lines" aria-label="Loading customers"><i></i><i></i><i></i></div>
      {:else if customers.length === 0}
        <div class="empty-state"><span>∅</span><h3>The ledger is clear.</h3><p>Make the first customer entry at right.</p></div>
      {:else}
        <div class="table-wrap">
          <table>
            <thead><tr><th>Customer</th><th>Status</th><th>Owner</th><th>Annual revenue</th></tr></thead>
            <tbody>
              {#each customers as customer (customer.id)}
                <tr>
                  <td><strong>{customer.data.name}</strong><small>{customer.id}</small></td>
                  <td><span class:paused={customer.data.status === "paused"} class="badge">{customer.data.status}</span></td>
                  <td>{customer.data.owner}</td>
                  <td class="revenue">{money(customer.data.annual_revenue)}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </section>

    <aside class="entry-form entry entry-four" aria-labelledby="entry-title">
      {#if signedIn}
        <p class="kicker">02 / new entry</p>
        <h2 id="entry-title">Add a customer</h2>
        <p class="form-intro">Each post carries a fresh idempotency key, so a retry stays one entry.</p>
        <form onsubmit={(event) => { event.preventDefault(); void createCustomer(); }}>
          <label>Name <input bind:value={name} autocomplete="organization" required placeholder="Acme Supply Co." /></label>
          <label>Status <select bind:value={status}><option value="active">Active</option><option value="paused">Paused</option></select></label>
          <label>Owner <input bind:value={owner} autocomplete="name" /></label>
          <label>Annual revenue <span class="input-affix">USD</span><input bind:value={annualRevenue} inputmode="decimal" placeholder="0.00" /></label>
          <button class="post" type="submit" disabled={submitting}>{submitting ? "Posting entry…" : "Post to ledger"} <span aria-hidden="true">→</span></button>
        </form>
      {:else}
        <p class="kicker">02 / access</p>
        <h2 id="entry-title">Sign in</h2>
        <p class="form-intro">Use a Framekit account to read and post customer records. Credentials stay in this form only.</p>
        <form onsubmit={(event) => { event.preventDefault(); void signIn(); }}>
          <label>Email <input bind:value={email} type="email" autocomplete="username" required /></label>
          <label>Password <input bind:value={password} type="password" autocomplete="current-password" required /></label>
          <button class="post" type="submit" disabled={authenticating}>{authenticating ? "Signing in…" : "Open ledger"} <span aria-hidden="true">→</span></button>
        </form>
      {/if}
    </aside>
  </div>

  <footer><span>Framekit SDK v2</span><span>Customer doctype / direct API example</span></footer>
</main>

// examples/frontends/vue/src/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from "vue";
import { FramekitSdkError, type HealthResponse } from "@framekit/sdk";
import { baseUrl, createFramekitClient } from "./framekit";

type CustomerFields = {
  name: string;
  status: "active" | "paused";
  owner: string;
  annual_revenue: string;
};

type CustomerRecord = { id: string; data: CustomerFields };
type MetaSummary = { name?: string; version?: string; modules?: Array<{ doctypes?: unknown[] }> };

const customers = ref<CustomerRecord[]>([]);
const health = ref<HealthResponse>();
const metadata = ref<MetaSummary>();
const loading = ref(true);
const refreshing = ref(false);
const submitting = ref(false);
const authenticating = ref(false);
const loggingOut = ref(false);
const signedIn = ref(false);
const error = ref<FramekitSdkError>();
const successMessage = ref("");
const form = reactive<CustomerFields>({ name: "", status: "active", owner: "Sales", annual_revenue: "0.00" });
const credentials = reactive({ email: "admin@example.com", password: "" });
let framekit = createFramekitClient();
let mounted = true;
let sessionGeneration = 0;
let sessionController = new AbortController();
let healthController = new AbortController();

const appName = computed(() => metadata.value?.name ?? health.value?.app ?? "Framekit");
const appVersion = computed(() => metadata.value?.version);
const doctypeCount = computed(() => metadata.value?.modules?.flatMap((module) => module.doctypes ?? []).length ?? 0);
const hasCustomers = computed(() => customers.value.length > 0);

onMounted(() => void loadHealth());
onUnmounted(() => {
  mounted = false;
  healthController.abort();
  invalidateSession();
});

async function loadHealth() {
  const controller = healthController;
  error.value = undefined;
  loading.value = true;
  try {
    const nextHealth = await framekit.health({ signal: controller.signal });
    if (!isHealthCurrent(controller)) return;
    health.value = nextHealth;
  } catch (caught) {
    if (!isHealthCurrent(controller)) return;
    error.value = asSdkError(caught);
  } finally {
    if (!isHealthCurrent(controller)) return;
    loading.value = false;
  }
}

async function loadLedger(generation = sessionGeneration) {
  if (!isSessionCurrent(generation)) return;
  const controller = sessionController;
  error.value = undefined;
  successMessage.value = "";
  refreshing.value = true;
  try {
    const [nextMetadata, page] = await Promise.all([
      framekit.meta<MetaSummary>(),
      framekit.listPage<CustomerFields>("customer", { limit: 50, sort: { field: "name", direction: "asc" }, signal: controller.signal })
    ]);
    if (!isSessionCurrent(generation, controller)) return;
    metadata.value = nextMetadata;
    customers.value = page.items;
  } catch (caught) {
    if (!isSessionCurrent(generation, controller)) return;
    error.value = asSdkError(caught);
  } finally {
    if (!isSessionCurrent(generation, controller)) return;
    refreshing.value = false;
  }
}

async function signIn() {
  const generation = beginSession();
  error.value = undefined;
  successMessage.value = "";
  authenticating.value = true;
  try {
    await framekit.login(credentials.email, credentials.password);
    if (!isGenerationCurrent(generation)) return;
    credentials.password = "";
    signedIn.value = true;
    await loadLedger(generation);
  } catch (caught) {
    if (!isGenerationCurrent(generation)) return;
    error.value = asSdkError(caught);
  } finally {
    if (!isGenerationCurrent(generation)) return;
    authenticating.value = false;
  }
}

async function signOut() {
  const generation = invalidateSession();
  const client = framekit;
  error.value = undefined;
  loggingOut.value = true;
  try {
    await client.logout();
  } catch (caught) {
    if (!isGenerationCurrent(generation)) return;
    error.value = asSdkError(caught);
  } finally {
    if (!isGenerationCurrent(generation)) return;
    framekit = createFramekitClient();
    signedIn.value = false;
    metadata.value = undefined;
    customers.value = [];
    successMessage.value = "";
    credentials.password = "";
    loggingOut.value = false;
  }
}

async function createCustomer() {
  const generation = sessionGeneration;
  if (!isSessionCurrent(generation)) return;
  const controller = sessionController;
  error.value = undefined;
  successMessage.value = "";
  submitting.value = true;
  try {
    const created = await framekit.create<CustomerFields>("customer", { ...form }, { idempotencyKey: createIdempotencyKey(), signal: controller.signal });
    if (!isSessionCurrent(generation, controller)) return;
    customers.value = [created, ...customers.value];
    successMessage.value = `${created.data.name} entered in the ledger.`;
    form.name = "";
    form.status = "active";
    form.owner = "Sales";
    form.annual_revenue = "0.00";
  } catch (caught) {
    if (!isSessionCurrent(generation, controller)) return;
    error.value = asSdkError(caught);
  } finally {
    if (!isSessionCurrent(generation, controller)) return;
    submitting.value = false;
  }
}

function beginSession() {
  invalidateSession();
  framekit = createFramekitClient();
  return sessionGeneration;
}

function invalidateSession() {
  sessionGeneration += 1;
  sessionController.abort();
  sessionController = new AbortController();
  return sessionGeneration;
}

function isHealthCurrent(controller: AbortController) {
  return mounted && controller === healthController && !controller.signal.aborted;
}

function isSessionCurrent(generation: number, controller = sessionController) {
  return mounted && signedIn.value && generation === sessionGeneration && controller === sessionController && !controller.signal.aborted;
}

function isGenerationCurrent(generation: number) {
  return mounted && generation === sessionGeneration && !sessionController.signal.aborted;
}

function asSdkError(caught: unknown): FramekitSdkError {
  if (caught instanceof FramekitSdkError) return caught;
  return new FramekitSdkError(
    caught instanceof Error ? caught.message : "An unexpected request error occurred.",
    "UNKNOWN_ERROR",
    undefined,
    undefined,
    undefined,
    undefined,
    { cause: caught }
  );
}

function createIdempotencyKey() {
  return `customer-${crypto.randomUUID()}`;
}

function currency(value: string) {
  const number = Number(value);
  return Number.isFinite(number)
    ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(number)
    : value;
}
</script>

<template>
  <main class="ledger-shell">
    <header class="masthead entry entry-one">
      <div>
        <p class="eyebrow">FRAMEKIT / CUSTOMER REGISTER</p>
        <h1>Field<br /><em>ledger.</em></h1>
      </div>
      <div class="masthead-note" aria-label="Connection details">
        <span class="status-dot" :class="{ alive: health?.ok }" aria-hidden="true"></span>
        <span>{{ health?.ok ? "live connection" : "awaiting connection" }}</span>
        <code>{{ baseUrl || "same-origin API proxy" }}</code>
      </div>
    </header>

    <section class="rule entry entry-two" aria-label="Ledger summary">
      <p>{{ appName }} <span v-if="appVersion">· v{{ appVersion }}</span></p>
      <p v-if="signedIn">{{ doctypeCount }} document types / {{ customers.length }} customers in view</p>
      <p v-else>Sign in to open protected records</p>
    </section>

    <section v-if="error" class="notice error entry" role="alert">
      <strong>{{ error.name }} · {{ error.code }}</strong>
      <span>{{ error.message }}</span>
      <small v-if="error.status">HTTP {{ error.status }}</small>
      <small v-if="error.requestId">request {{ error.requestId }}</small>
    </section>
    <section v-else-if="successMessage" class="notice success entry" role="status">{{ successMessage }}</section>

    <div class="ledger-grid">
      <section class="customer-panel entry entry-three" aria-labelledby="customer-list-title" :aria-busy="loading || refreshing">
        <div class="section-heading">
          <div>
            <p class="eyebrow">01 / CURRENT ACCOUNTS</p>
            <h2 id="customer-list-title">Customers</h2>
          </div>
          <button v-if="signedIn" class="text-button" type="button" :disabled="refreshing" @click="() => loadLedger()">
            {{ refreshing ? "Refreshing…" : "Refresh list" }}
          </button>
        </div>

        <div v-if="loading" class="state-card" role="status">Checking the line…</div>
        <div v-else-if="!signedIn" class="state-card empty">
          <span>Ledger sealed.</span>
          <p>Use the sign-in slip to open customer records.</p>
        </div>
        <div v-else-if="!hasCustomers" class="state-card empty">
          <span>Nothing recorded.</span>
          <p>Add the first customer using the intake card.</p>
        </div>
        <ol v-else class="customer-list">
          <li v-for="customer in customers" :key="customer.id">
            <div class="customer-name">
              <strong>{{ customer.data.name }}</strong>
              <span>{{ customer.data.owner }}</span>
            </div>
            <span class="badge" :class="customer.data.status">{{ customer.data.status }}</span>
            <span class="revenue">{{ currency(customer.data.annual_revenue) }}</span>
          </li>
        </ol>
      </section>

      <section v-if="signedIn" class="intake-panel entry entry-four" aria-labelledby="intake-title">
        <div class="intake-heading">
          <div>
            <p class="eyebrow">02 / INTAKE SLIP</p>
            <h2 id="intake-title">Enter a customer</h2>
          </div>
          <button class="logout-button" type="button" :disabled="loggingOut" @click="signOut">{{ loggingOut ? "Leaving…" : "Sign out" }}</button>
        </div>
        <form @submit.prevent="createCustomer">
          <label>
            <span>Name</span>
            <input v-model.trim="form.name" required autocomplete="organization" placeholder="Northstar Goods" />
          </label>
          <div class="split-fields">
            <label>
              <span>Status</span>
              <select v-model="form.status">
                <option value="active">Active</option>
                <option value="paused">Paused</option>
              </select>
            </label>
            <label>
              <span>Owner</span>
              <input v-model.trim="form.owner" required autocomplete="name" />
            </label>
          </div>
          <label>
            <span>Annual revenue</span>
            <input v-model="form.annual_revenue" required inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" aria-describedby="revenue-note" />
            <small id="revenue-note">Numbers only, in USD.</small>
          </label>
          <button class="submit-button" type="submit" :disabled="submitting">
            <span>{{ submitting ? "Recording…" : "Record customer" }}</span>
            <b aria-hidden="true">↗</b>
          </button>
        </form>
        <p class="idempotency-note">Each submission carries a fresh idempotency key.</p>
      </section>
      <section v-else class="intake-panel entry entry-four" aria-labelledby="sign-in-title">
        <p class="eyebrow">02 / ACCESS SLIP</p>
        <h2 id="sign-in-title">Sign in</h2>
        <form @submit.prevent="signIn">
          <label>
            <span>Email</span>
            <input v-model.trim="credentials.email" type="email" required autocomplete="username" />
          </label>
          <label>
            <span>Password</span>
            <input v-model="credentials.password" type="password" required autocomplete="current-password" />
          </label>
          <button class="submit-button" type="submit" :disabled="authenticating || loading">
            <span>{{ authenticating ? "Opening…" : "Open ledger" }}</span>
            <b aria-hidden="true">↗</b>
          </button>
        </form>
        <p class="idempotency-note">Session credentials remain only in this browser tab’s memory.</p>
      </section>
    </div>

    <footer class="footer-rule entry entry-four">
      <span>Framekit SDK v2</span><span>Default tenant / app context</span><span>No token persisted</span>
    </footer>
  </main>
</template>
