// examples/frontends/solid/src/state/useLedger.ts
import { createSignal, onCleanup, onMount } from "solid-js";
import { FramekitSdkError, type HealthResponse } from "@framekit/sdk";
import { type Customer, type CustomerFormValues, type CustomerRecord, initialCustomerForm } from "../domain/customer";
import { clearClientSession, client } from "../lib/api/framekit";

type RequestGuard = { generation: number; controller: AbortController };

function messageFor(error: unknown): string {
  if (error instanceof FramekitSdkError) {
    const request = error.requestId ? ` Request: ${error.requestId}.` : "";
    return `${error.code}${error.status ? ` (${error.status})` : ""}: ${error.message}.${request}`;
  }
  return error instanceof Error ? error.message : "An unexpected error occurred.";
}

function idempotencyKey(): string {
  return globalThis.crypto?.randomUUID?.() ?? `solid-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

export function useLedger() {
  const [customers, setCustomers] = createSignal<CustomerRecord[]>([]);
  const [health, setHealth] = createSignal<HealthResponse>();
  const [metadata, setMetadata] = createSignal<unknown>();
  const [loading, setLoading] = createSignal(true);
  const [authenticated, setAuthenticated] = createSignal(false);
  const [signingIn, setSigningIn] = createSignal(false);
  const [submitting, setSubmitting] = createSignal(false);
  const [error, setError] = createSignal<string>();
  const [success, setSuccess] = createSignal<string>();
  const [form, setForm] = createSignal<CustomerFormValues>(initialCustomerForm());
  const [email, setEmail] = createSignal("admin@example.com");
  const [password, setPassword] = createSignal("");
  let mounted = true;
  let sessionGeneration = 0;
  const activeControllers = new Set<AbortController>();

  const beginRequest = (): RequestGuard => {
    const controller = new AbortController();
    activeControllers.add(controller);
    return { generation: sessionGeneration, controller };
  };
  const finishRequest = (request: RequestGuard): void => {
    activeControllers.delete(request.controller);
  };
  const isCurrent = (request: RequestGuard): boolean => mounted && request.generation === sessionGeneration && !request.controller.signal.aborted;
  const invalidateSession = (): void => {
    sessionGeneration += 1;
    for (const controller of activeControllers) controller.abort();
    activeControllers.clear();
  };

  const checkHealth = async (): Promise<void> => {
    const request = beginRequest();
    setLoading(true);
    try {
      const nextHealth = await client.health({ signal: request.controller.signal });
      if (isCurrent(request)) setHealth(nextHealth);
    } catch (cause) {
      if (isCurrent(request)) setError(messageFor(cause));
    } finally {
      if (isCurrent(request)) setLoading(false);
      finishRequest(request);
    }
  };

  const load = async (): Promise<void> => {
    if (!authenticated()) return;
    const request = beginRequest();
    setLoading(true);
    setError(undefined);
    try {
      const [nextMetadata, page] = await Promise.all([
        client.meta(),
        client.listPage<Customer>("customer", { limit: 25, sort: { field: "name", direction: "asc" }, signal: request.controller.signal })
      ]);
      if (isCurrent(request)) {
        setMetadata(nextMetadata);
        setCustomers(page.items);
      }
    } catch (cause) {
      if (isCurrent(request)) setError(messageFor(cause));
    } finally {
      if (isCurrent(request)) setLoading(false);
      finishRequest(request);
    }
  };

  const signIn = async (event: SubmitEvent): Promise<void> => {
    event.preventDefault();
    invalidateSession();
    const request = beginRequest();
    setSigningIn(true);
    setError(undefined);
    try {
      await client.login(email(), password());
      if (!isCurrent(request)) return;
      setAuthenticated(true);
      setPassword("");
      setSuccess("Signed in. Customer records are ready.");
      setSigningIn(false);
      void load();
    } catch (cause) {
      if (isCurrent(request)) {
        setError(messageFor(cause));
        setSigningIn(false);
      }
    } finally {
      finishRequest(request);
    }
  };

  const signOut = async (): Promise<void> => {
    const logoutClient = client;
    invalidateSession();
    const logoutGeneration = sessionGeneration;
    clearClientSession();
    setError(undefined);
    setAuthenticated(false);
    setCustomers([]);
    setMetadata(undefined);
    setSuccess(undefined);
    setLoading(false);
    setSigningIn(false);
    setSubmitting(false);
    try {
      await logoutClient.logout();
    } catch (cause) {
      if (mounted && sessionGeneration === logoutGeneration) setError(messageFor(cause));
    }
  };

  const createCustomer = async (event: SubmitEvent): Promise<void> => {
    event.preventDefault();
    const request = beginRequest();
    setSubmitting(true);
    setError(undefined);
    setSuccess(undefined);
    try {
      const customer = await client.create<Customer>("customer", form(), { idempotencyKey: idempotencyKey(), signal: request.controller.signal });
      if (isCurrent(request)) {
        setCustomers((current) => [customer, ...current]);
        setForm(initialCustomerForm());
        setSuccess(`${customer.data.name || "Customer"} added to the ledger.`);
      }
    } catch (cause) {
      if (isCurrent(request)) setError(messageFor(cause));
    } finally {
      if (isCurrent(request)) setSubmitting(false);
      finishRequest(request);
    }
  };

  onMount(() => void checkHealth());
  onCleanup(() => {
    mounted = false;
    invalidateSession();
  });

  return { customers, health, metadata, loading, authenticated, signingIn, submitting, error, success, form, email, password, setForm, setEmail, setPassword, load, signIn, signOut, createCustomer };
}

// examples/frontends/react/src/hooks/useLedger.ts
import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { type FramekitClient, type HealthResponse } from "@framekit/sdk";
import { createClient } from "../api/framekit";
import { type Customer, type CustomerData, type CustomerForm, emptyCustomerForm, type LedgerMeta } from "../domain/customer";

export function useLedger() {
  const clientRef = useRef(createClient());
  const generationRef = useRef(0);
  const listControllerRef = useRef<AbortController | undefined>(undefined);
  const mountedRef = useRef(true);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [health, setHealth] = useState<HealthResponse>();
  const [meta, setMeta] = useState<LedgerMeta>();
  const [healthLoading, setHealthLoading] = useState(true);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [signingIn, setSigningIn] = useState(false);
  const [signedIn, setSignedIn] = useState(false);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<unknown>();
  const [form, setForm] = useState<CustomerForm>(emptyCustomerForm);

  const isCurrent = useCallback((generation: number, client: FramekitClient) => (
    mountedRef.current && generationRef.current === generation && clientRef.current === client
  ), []);

  const loadLedger = useCallback(async (client: FramekitClient, generation: number) => {
    listControllerRef.current?.abort();
    const controller = new AbortController();
    listControllerRef.current = controller;
    if (!isCurrent(generation, client)) return;
    setLoading(true);
    setError(undefined);
    try {
      const [nextMeta, page] = await Promise.all([
        client.meta<LedgerMeta>(),
        client.listPage<CustomerData>("customer", { limit: 20, signal: controller.signal })
      ]);
      if (isCurrent(generation, client) && !controller.signal.aborted) {
        setMeta(nextMeta);
        setCustomers(page.items);
      }
    } catch (failure) {
      if (isCurrent(generation, client) && !controller.signal.aborted) setError(failure);
    } finally {
      if (isCurrent(generation, client) && !controller.signal.aborted) {
        setLoading(false);
        setRefreshing(false);
      }
    }
  }, [isCurrent]);

  useEffect(() => {
    mountedRef.current = true;
    const controller = new AbortController();
    const client = clientRef.current;
    void client.health({ signal: controller.signal }).then((nextHealth) => {
      if (mountedRef.current && clientRef.current === client) setHealth(nextHealth);
    }).catch((failure: unknown) => {
      if (mountedRef.current && !controller.signal.aborted && clientRef.current === client) setError(failure);
    }).finally(() => {
      if (mountedRef.current && !controller.signal.aborted && clientRef.current === client) setHealthLoading(false);
    });
    return () => {
      mountedRef.current = false;
      controller.abort();
      listControllerRef.current?.abort();
      generationRef.current += 1;
    };
  }, []);

  const refresh = () => {
    const client = clientRef.current;
    const generation = generationRef.current;
    setRefreshing(true);
    void loadLedger(client, generation);
  };

  const signIn = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const email = String(data.get("email") ?? "");
    const password = String(data.get("password") ?? "");
    listControllerRef.current?.abort();
    const generation = generationRef.current + 1;
    generationRef.current = generation;
    const client = createClient();
    clientRef.current = client;
    setSigningIn(true);
    setError(undefined);
    try {
      await client.login(email, password);
      if (!isCurrent(generation, client)) return;
      setSignedIn(true);
      await loadLedger(client, generation);
    } catch (failure) {
      if (isCurrent(generation, client)) setError(failure);
    } finally {
      if (isCurrent(generation, client)) setSigningIn(false);
    }
  };

  const logout = async () => {
    const client = clientRef.current;
    listControllerRef.current?.abort();
    const generation = generationRef.current + 1;
    generationRef.current = generation;
    try {
      await client.logout();
    } catch (failure) {
      if (mountedRef.current && generationRef.current === generation) setError(failure);
    } finally {
      if (generationRef.current !== generation) return;
      clientRef.current = createClient();
      if (mountedRef.current) {
        setSignedIn(false);
        setCustomers([]);
        setMeta(undefined);
        setForm(emptyCustomerForm);
        setLoading(false);
        setRefreshing(false);
        setCreating(false);
      }
    }
  };

  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const client = clientRef.current;
    const generation = generationRef.current;
    setCreating(true);
    setError(undefined);
    try {
      await client.create<CustomerData>("customer", {
        name: form.name.trim(), status: form.status, owner: form.owner.trim(), annual_revenue: form.annual_revenue
      }, { idempotencyKey: crypto.randomUUID() });
      if (!isCurrent(generation, client)) return;
      setForm(emptyCustomerForm);
      await loadLedger(client, generation);
    } catch (failure) {
      if (isCurrent(generation, client)) setError(failure);
    } finally {
      if (isCurrent(generation, client)) setCreating(false);
    }
  };

  return { customers, health, meta, healthLoading, loading, refreshing, signingIn, signedIn, creating, error, form, setForm, refresh, signIn, logout, submit };
}
